### ISSUE TITLE
ItemSetType item_idx greater than 255 turn 0++

### ISSUE THREAD

**Issue by rooanoliveira** [VDraven/MuClientTools16#6]
All Lines with item_idx greater than 255 are coming with calc item_idx = 0++
256 = 0 / 257 = 1 / 258 = 2 / 259 = 3 and +++

**Comment by VDraven** [comment]
Fixed. Thanks for testing.
https://github.com/VD1988/MuClientTools16/commit/933d218501c188363096a8f9f73720c61b535d06
